export const alias = (prefix = './src') => ({
  '@components': `${prefix}/app/components`,
  '@pages': `${prefix}/app/pages`,
  '@types': `${prefix}/types`,
  '@styles': `${prefix}/app/assets/styles`,
  '@utils': `${prefix}/utils`,
  '@apis': `${prefix}/apis`,
  '@assets': `${prefix}/app/assets`,
  '@i18n': `${prefix}/i18n`,
  '@config': `${prefix}/config`,
  '@routers': `${prefix}/routers`,
  '@constants': `${prefix}/utils/constants`,
  '@hooks': `${prefix}/app/hooks`,
  '@layouts': `${prefix}/layout`,
  '@stores': `${prefix}/store`,
});
